export * as xml from './xml/index.js';
export * as zip from './zip/index.js';
export * as units from '../units/index.js';

export type { DocierErrorCode, DocierErrorOptions, DocierParseErrorOptions } from './errors.js';
export { DocierError, DocierParseError, isDocierError, isDocierParseError } from './errors.js';

export {
  A_NAMESPACE,
  A_STRICT_NAMESPACE,
  ACTIVE_X_DIRECTORY,
  C_NAMESPACE,
  CONFORMANCE_NAMESPACE_MAP,
  CONTENT_TYPES_NAMESPACE,
  CONTENT_TYPES_PART_NAME,
  CORE_PROPERTIES_NAMESPACE,
  CUSTOM_PROPERTIES_NAMESPACE,
  CUSTOM_XML_DIRECTORY,
  CUSTOM_XML_PROPERTIES_NAMESPACE,
  DC_NAMESPACE,
  DCMITYPE_NAMESPACE,
  DCTERMS_NAMESPACE,
  DEFAULT_PREFIXES,
  DGM_NAMESPACE,
  DOCPROPS_VT_NAMESPACE,
  DOC_PROPS_DIRECTORY,
  EMBEDDINGS_DIRECTORY,
  EXTENDED_PROPERTIES_NAMESPACE,
  GLOSSARY_DOCUMENT_PART_NAME,
  M_NAMESPACE,
  M_STRICT_NAMESPACE,
  MAIN_DOCUMENT_PART_NAME,
  MC_NAMESPACE,
  MEDIA_DIRECTORY,
  OFFICE_NAMESPACE,
  PACKAGE_RELATIONSHIPS_NAMESPACE,
  PACKAGE_RELATIONSHIPS_PART_NAME,
  PACKAGE_ROOT_PART_NAME,
  PIC_NAMESPACE,
  PIC_STRICT_NAMESPACE,
  PREFIX_A,
  PREFIX_C,
  PREFIX_M,
  PREFIX_MC,
  PREFIX_O,
  PREFIX_PIC,
  PREFIX_R,
  PREFIX_V,
  PREFIX_W,
  PREFIX_W14,
  PREFIX_W15,
  PREFIX_W16,
  PREFIX_WP,
  PREFIX_WPG,
  PREFIX_WPS,
  PREFIX_XML,
  PRINTER_SETTINGS_DIRECTORY,
  R_NAMESPACE,
  RELATIONSHIPS_DIRECTORY,
  RELATIONSHIPS_EXTENSION,
  RELATIONSHIP_TYPES,
  RELATIONSHIP_TYPE_CORE_PROPERTIES,
  RELATIONSHIP_TYPE_DIGITAL_SIGNATURE,
  RELATIONSHIP_TYPE_DIGITAL_SIGNATURE_ORIGIN,
  RELATIONSHIP_TYPE_IMAGE,
  RELATIONSHIP_TYPE_OFFICE_DOCUMENT,
  RELATIONSHIP_TYPE_TARGET_MODE_EXTERNAL,
  RELATIONSHIP_TYPE_TARGET_MODE_INTERNAL,
  RELATIONSHIP_TYPE_THUMBNAIL,
  R_STRICT_NAMESPACE,
  VML_NAMESPACE,
  W14_NAMESPACE,
  W15_NAMESPACE,
  W16CEX_NAMESPACE,
  W16CID_NAMESPACE,
  W16DU_NAMESPACE,
  W16_NAMESPACE,
  WNE_NAMESPACE,
  WORD_2003_NAMESPACE,
  WPC_NAMESPACE,
  WPG_NAMESPACE,
  WPS_NAMESPACE,
  WP_NAMESPACE,
  WP_STRICT_NAMESPACE,
  W_NAMESPACE,
  W_STRICT_NAMESPACE,
  XMLNS_NAMESPACE,
  XML_DIGITAL_SIGNATURE_NAMESPACE,
  XML_NAMESPACE,
  XML_SIGNATURES_DIRECTORY,
  defaultPrefixFor,
  qualifiedName,
  toStrictNamespace,
  toStrictRelationshipType,
} from './namespaces.js';

export type { TextEncoding } from './bytes.js';
export {
  ENCODING_ALIASES,
  asUint8Array,
  bytesEqual,
  concatBytes,
  decodeText,
  decodeUtf8,
  encodeText,
  encodeUtf16,
  encodeUtf8,
  encodingLabel,
  readUint8,
  resolveEncoding,
  tryDecodeUtf8,
} from './bytes.js';

export { SHA256_DIGEST_BYTES, SHA256_HEX_LENGTH, sha256, sha256Hex, toHex } from './sha256.js';

export type { DeflateBackend, DeflateFlavour, DeflateResolution } from './zip/index.js';
export {
  DEFLATE_LEVEL,
  getPinnedDeflateBackend,
  resolveDeflateBackend,
  setPinnedDeflateBackend,
} from './zip/index.js';

export type {
  ContentTypeDefault,
  ContentTypeDiagnostic,
  ContentTypeOverride,
} from './content-types.js';
export {
  CONTENT_TYPE_ACTIVE_X,
  CONTENT_TYPE_ACTIVE_X_XML,
  CONTENT_TYPE_CORE_PROPERTIES,
  CONTENT_TYPE_CUSTOM_PROPERTIES,
  CONTENT_TYPE_EXTENDED_PROPERTIES,
  CONTENT_TYPE_OBFUSCATED_FONT,
  CONTENT_TYPE_OLE_OBJECT,
  CONTENT_TYPE_PRINTER_SETTINGS,
  CONTENT_TYPE_RELATIONSHIPS,
  CONTENT_TYPE_THEME,
  CONTENT_TYPE_VBA_DATA,
  CONTENT_TYPE_VBA_PROJECT,
  CONTENT_TYPE_XML,
  ContentTypes,
  DEFAULT_CONTENT_TYPES,
  MACRO_DOCUMENT_CONTENT_TYPE,
  MACRO_TEMPLATE_CONTENT_TYPE,
  MAIN_DOCUMENT_CONTENT_TYPE,
  TEMPLATE_CONTENT_TYPE,
  WORD_MAIN_CONTENT_TYPES,
  extensionOf,
  fromOverridePartName,
  isWordMainContentType,
  toOverridePartName,
} from './content-types.js';

export type {
  Relationship,
  RelationshipDiagnostic,
  RelationshipDiagnosticCode,
  RelationshipSpec,
  RelationshipTargetMode,
  RelationshipValidationTarget,
} from './relationships.js';
export {
  RELATIONSHIP_ATTRIBUTE_ID,
  RELATIONSHIP_ATTRIBUTE_TARGET,
  RELATIONSHIP_ATTRIBUTE_TARGET_MODE,
  RELATIONSHIP_ATTRIBUTE_TYPE,
  RelationshipGraph,
  RelationshipsPart,
  compareRelationshipIds,
  directoryOf,
  isAnchorTarget,
  isRelationshipsPartName,
  normalisePartName,
  relationshipTypeLocalName,
  relationshipsPartNameFor,
  relativeTargetFor,
  resolveRelationshipTarget,
  sourcePartNameFor,
} from './relationships.js';

export type { PartContent, PartEnvironment, PartOptions, PartWritePlan } from './part.js';
export { Part } from './part.js';

export type { AllocatePartNameOptions, PartKind, PartNamingConvention, PartRole } from './part-kinds.js';
export {
  NAMING_CONVENTIONS,
  PACKAGE_PART_KINDS,
  PART_KINDS,
  PART_ROLES_WITH_FIXED_NAME,
  STORED_EXTENSIONS,
  allocatePartName,
  contentTypeForRole,
  isEmbeddingPartName,
  isGlossaryPartName,
  isMediaPartName,
  isSignaturePartName,
  isStoryRole,
  isThumbnailPartName,
  isXmlRole,
  namingConventionFor,
  partKindForRole,
  relationshipTypeForRole,
  roleForContentType,
  roleForRelationshipType,
  usesStoredCompression,
} from './part-kinds.js';

export type {
  BlobFactory,
  DocumentKind,
  FidelityFinding,
  MediaPartResult,
  OpenPackageOptions,
  PackageDiagnostic,
  PackageDiagnosticCode,
  PackageDiagnosticSeverity,
  PackageSource,
  PackageValidationFinding,
  SavePackageOptions,
} from './package.js';
export { DEFAULT_MAX_PACKAGE_BYTES, DEFAULT_MAX_PART_BYTES, DocxPackage, roleOfPart } from './package.js';
